name: docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the addons branch
  push:
    branches:
      - readwrite-analysis

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Image Version
        id: set-version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/lizalc/codeclimate/codeclimate:latest
            ghcr.io/lizalc/codeclimate/codeclimate:${{ env.VERSION }}
